
services:
  frontend:
    image: aslesha18/ai-avatar-frontend:latest
    container_name: ai-avatar-frontend
    ports:
      - "80:80"
    networks:
      - ai-avatar-network

networks:
  ai-avatar-network:
    external: true
